# default configuration
baseURL = "https://juliazolyomi.com"
languageCode = "en-us"
summaryLength = "10"
#theme = "ananke"
title = "Julia Zolyomi"
staticDir = "static"
googleAnalytics = "UA-170856231-1"
enableRobotsTXT = true

DefaultContentLanguage = "en"
copyright = "Julia Zolyomi"

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  favicon = ""
  description = ""
  #linkedin = "https://www.linkedin.com/in/julia-zolyomi"
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  custom_css = ["style.css"]
  body_classes= "avenir"
  #featured_image = "/images/backgrounds/10.jpg"
  cover_dimming_class = "header-dimming"
  featured_image = "/images/backgrounds/8.png"
  recent_posts_number = 2

[languages]
  [languages.en]
    title = "Julia Zolyomi"
    subTitle = "Psychologist"
    #baseURL = "https://juliazolyomi.com"
    homeURL = "/"
    #staticDir = "static"
    languageName = "English"
    weight = 1
    [languages.en.params]
      #linkedin = "https://www.linkedin.com/in/julia-zolyomi"

  [[languages.en.menu.main]]
    url    = "/counseling"
    name   = "Counseling"
    weight = 10

  [[languages.en.menu.main]]
    url    = "/about-me"
    name   = "About Me"
    weight = 20

  [[languages.en.menu.main]]
    url    = "/feedback"
    name   = "Feedback"
    weight = 30

  [[languages.en.menu.main]]
    url    = "/contact"
    name   = "Contact"
    weight = 40

  [languages.hu]
    title = "Zólyomi Júlia"
    subTitle = "Pszichológus"
    #baseURL = "https://juliazolyomi.com/hu"
    homeURL = "/hu"
    #staticDir = "static"
    languageName = "Magyar"
    weight = 2
    [languages.hu.params]
      #linkedin = "https://www.linkedin.com/in/julia-zolyomi"

  [[languages.hu.menu.main]]
    url    = "/hu"
    name   = "Tanácsadás"
    weight = 10

  [[languages.hu.menu.main]]
    url    = "/magamrol"
    name   = "Magamról"
    weight = 20

  [[languages.hu.menu.main]]
    url    = "/velemenyek"
    name   = "Vélemények"
    weight = 30

  [[languages.hu.menu.main]]
    url    = "/kapcsolat"
    name   = "Kapcsolat"
    weight = 40
